// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "",
  source: "permissions.typ",
  "raw-langs": ("bash", "d2", "dot", "json", "mermaid", "python", "r", "text", "tikz", "toml"),
)
