[platform.exec]
rox = [
  "/bin",
  "/usr/bin",
  "/usr/local/bin",
  "~/.local/bin",
  "~/.bin",
]

[platform.libs]
ro = [
  "/etc/ssl",
  "/etc/pki",
  "/etc/ca-certificates",
  "/usr/share/ca-certificates",
  "/usr/local/share/ca-certificates",
  "/etc/resolv.conf",
  "/etc/hosts",
  "/etc/nsswitch.conf",
  "/proc/self",
  "/dev/null",
  "/dev/urandom",
]
rox = [
  "/lib",
  "/lib64",
  "/usr/lib",
  "/usr/lib64",
]
