[platform.macos.exec]
rox = [
  "/bin",
  "/usr/bin",
  "/sbin",
  "/usr/local/bin",
  "~/.local/bin",
  "~/.bin",
  "~/.cargo/bin",
  "/opt/homebrew/bin",
]

[platform.macos.libs]
ro = [
  "/etc",
  "/private/etc",
  "/usr/share",
  "/usr/local/etc",
  "/usr/local/share",
  "/opt/homebrew/etc",
  "/opt/homebrew/share",
  "/System/Library",
  "/Library/Preferences/SystemConfiguration",
  "/var/select",
]
rox = [
  "/usr/local/lib",
  "/usr/local/Cellar",
  "/usr/local/opt",
  "/opt/homebrew/lib",
  "/opt/homebrew/Cellar",
  "/opt/homebrew/opt",
  "/usr/lib",
]

[platform.linux.exec]
rox = [
  "/bin",
  "/usr/bin",
  "/sbin",
  "/usr/local/bin",
  "~/.local/bin",
  "~/.bin",
  "~/.cargo/bin",
]

[platform.linux.libs]
ro = [
  "/etc/ssl",
  "/etc/pki",
  "/etc/ca-certificates",
  "/usr/share/ca-certificates",
  "/usr/local/share/ca-certificates",
  "/etc/resolv.conf",
  "/etc/hosts",
  "/etc/nsswitch.conf",
  "/proc/self",
  "/dev/null",
  "/dev/urandom",
]
rox = [
  "/lib",
  "/lib64",
  "/usr/lib",
  "/usr/lib64",
]
